# Generated by Django 6.0.5 on 2026-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_companyservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn_base_price', models.PositiveIntegerField(default=5000)),
                ('osno_base_price', models.PositiveIntegerField(default=12000)),
                ('employee_price', models.PositiveIntegerField(default=700)),
                ('max_employees', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Калькулятор',
                'verbose_name_plural': 'Калькулятор',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('account_balance_wallet', 'Бухгалтерия'), ('badge', 'Кадры'), ('query_stats', 'Аудит'), ('gavel', 'Юридические услуги')], max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ZenAccounting', max_length=255)),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_title_colored', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('security_title', models.CharField(max_length=255)),
                ('security_description', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=15)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('footer_text', models.TextField()),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('offer_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyService',
        ),
    ]
