# Generated by Django 6.0.5 on 2026-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ipservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('resin', 'Смоляные фигурки'), ('clay', 'Полимерная глина'), ('doll', 'Арт-куклы'), ('diorama', 'Миниатюры')], max_length=100)),
                ('price', models.IntegerField(help_text='Цена в йенах')),
                ('image_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
